##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - test_mongo

- include: mariadb_install.yml
- include: mariadb_cluster.yml

- include: mariadb_config.yml
  when:
    - inventory_hostname == haproxy_hosts.keys()[0]

- include: mongodb_install.yml
  tags:
    - test_mongo

- include: mongodb_config.yml
  when:
    - inventory_hostname == haproxy_hosts.keys()[0]
  tags:
    - test_mongo

- meta: flush_handlers
