##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: disable auto start
  copy:
    content: "#!/bin/sh\nexit 101"
    dest: "/usr/sbin/policy-rc.d"
    mode: 0755
  when: ansible_os_family == "Debian"

- name: install python-mysqldb
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: maridb_packages | union(packages_noarch)

- name: change open file limit
  copy:
    content: "* - nofile 65536 }}"
    dest: "/etc/security/limits.conf"
    mode: 0755

- name: create conf dir for wsrep
  file: path=/etc/my.cnf.d state=directory mode=0755
  when: ansible_os_family == "RedHat"

- name: update mariadb config file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    backup: yes
    mode: 0644
  with_items: mysql_config

- name: bugfix for rsync version 3.1
  lineinfile:
    dest: /usr/bin/wsrep_sst_rsync
    state: absent
    regexp: '{{ item }}'
  with_items:
    - "\\s*uid = \\$MYUID$"
    - "\\s*gid = \\$MYGID$"

- name: enable auto start
  file:
    path=/usr/sbin/policy-rc.d
    state=absent
  when: ansible_os_family == "Debian"

- name: set owner
  file: path=/var/lib/mysql owner=mysql group=mysql recurse=yes state=directory

- name: get logfile stat
  stat: path='{{ mysql_data_dir }}/ib_logfile0'
  register: logfile_stat

- debug: msg='{{ logfile_stat.stat.exists}}'
- debug: msg='{{ logfile_stat.stat.size }}'
  when: logfile_stat.stat.exists

- name: rm logfile if exist and size mismatch
  shell: 'rm -rf {{ mysql_data_dir }}/ib_logfile*'
  when: |
    logfile_stat.stat.exists
    and logfile_stat.stat.size != 1073741824
