##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"

- include: glance_install.yml
  tags:
    - install
    - glance_install
    - glance

- include: nfs.yml
  tags:
    - nfs

- include: glance_config.yml
  when: inventory_hostname == groups['controller'][0]
  tags:
    - config
    - glance_config
    - glance

- meta: flush_handlers
