##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: restart haproxy
  service: name=haproxy state=restarted enabled=yes

- name: restart xinetd
  service: name=xinetd state=restarted enabled=yes

- name: restart keepalived
  service: name=keepalived state=restarted enabled=yes
