##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include: keystone_install.yml
  tags:
    - install
    - keystone_install
    - keystone

- include: keystone_config.yml
  when: inventory_hostname == groups['controller'][0]
  tags:
    - config
    - keystone_config
    - keystone

- meta: flush_handlers
