##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"

- name: remove neutron-plugin-openvswitch-agent auto start
  shell: >
    update-rc.d neutron-plugin-openvswitch-agent remove;
    sed -i /neutron-plugin-openvswitch-agent/d /opt/service
  when: groups['onos']|length !=0
  ignore_errors: True

- name: shut down and disable Neutron's agent services
  service: name=neutron-plugin-openvswitch-agent state=stopped
  when: groups['onos']|length !=0
  ignore_errors: True

- name: remove neutron-l3-agent auto start
  shell: >
    update-rc.d neutron-l3-agent remove;
    sed -i /neutron-l3-agent/d /opt/service
  when: inventory_hostname in groups['onos']
  ignore_errors: True

- name: shut down and disable Neutron's l3 agent services
  service: name=neutron-l3-agent state=stopped
  when: inventory_hostname in groups['onos']
  ignore_errors: True

- name: Stop the Open vSwitch service and clear existing OVSDB
  shell: >
    ovs-vsctl del-br br-int ;
    ovs-vsctl del-br br-tun ;
    ovs-vsctl del-manager ;
    ip link delete onos_port1 type veth peer name onos_port2;
  when: groups['onos']|length !=0
  ignore_errors: True

- name: Install ONOS Cluster on Controller
  include: onos_controller.yml
  when: inventory_hostname in groups['onos']

- name: Install ONOS Cluster on Compute
  include: openvswitch.yml
  when: groups['onos']|length !=0
#  when: groups['onos']|length !=0 and inventory_hostname not in groups['onos']

