##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
#- hosts: all
#  sudo: yes
#  tasks:
#- name: get last ip address
#  shell: expr substr `cat /etc/hostname` 5 1 
#  register: lastip

#- name: "configure interface"
##  sudo: True
#  lineinfile:
#    dest: "/etc/network/interfaces"
#    line: "{{ item }}"
#  with_items:
#    - "auto {{ contrail_vhost_device }}"
#    - "iface {{ contrail_vhost_device }} inet static"
#    - "\taddress {{ contrail_vhost_address }}"
#    - "\tnetmask {{ contrail_vhost_netmask }}"

- name: "set interface address"
#  sudo: True
  shell: "ifconfig {{ contrail_vhost_device }} {{ contrail_vhost_address }} netmask {{ contrail_vhost_netmask }}"

- name: "up interface"
#  sudo: True
  shell: "ifconfig {{ contrail_vhost_device }} up"
