##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
#- hosts: database
#  sudo: yes
#  tasks:
- name: "temporary disable supervisor database"
#  sudo: True
  template:
#        src: "templates/override.j2"
    src: "../../templates/install/override.j2"
    dest: "/etc/init/supervisor-database.override"

- name: "install contrail openstack database package"
#  sudo: True
#      apt:
#        name: "contrail-openstack-database"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present force=yes"
  with_items: database_package 
