##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"

- name: disable auto start
  copy:
    content: "#!/bin/sh\nexit 101"
    dest: "/usr/sbin/policy-rc.d"
    mode: 0755
  when: ansible_os_family == "Debian"

- name: install ceilometer packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: ceilometer_packages | union(packages_noarch)

- name: enable auto start
  file:
    path=/usr/sbin/policy-rc.d
    state=absent
  when: ansible_os_family == "Debian"

- name: copy ceilometer configs
  template: src={{ item.src}} dest=/opt/os_templates
  with_items: "{{ ceilometer_configs_templates }}"

- name: update ceilometer configs
  shell: crudini --merge {{ item.1 }} < /opt/os_templates/{{ item.0.src }}
  with_subelements:
    - ceilometer_configs_templates
    - dest
  notify: restart ceilometer relation service

- name: write services to monitor list
  lineinfile: dest=/opt/service create=yes line='{{ item }}'
  with_items: ceilometer_services

- meta: flush_handlers
