##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"

- name: disable auto start
  copy:
    content: "#!/bin/sh\nexit 101"
    dest: "/usr/sbin/policy-rc.d"
    mode: 0755
  when: ansible_os_family == "Debian"

- name: install vpn packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: vpn_packages

- name: enable auto start
  file:
    path=/usr/sbin/policy-rc.d
    state=absent
  when: ansible_os_family == "Debian"

- name: update vpn related conf
  shell: crudini --set  /etc/neutron/l3_agent.ini vpnagent vpn_device_driver neutron_vpnaas.services.vpn.device_drivers.strongswan_ipsec.StrongSwanDriver;
         crudini --set --list /etc/neutron/neutron.conf DEFAULT service_plugins vpnaas
         crudini --set /etc/neutron/neutron_vpnaas.conf service_providers service_provider 'VPN:strongswan:neutron_vpnaas.services.vpn.service_drivers.ipsec.IPsecVPNDriver:default'

- name: make sure rootwrap.d dir exist
  file: path=/etc/neutron/rootwrap.d state=directory mode=0755

- name: update rootwrap
  copy: src=vpnaas.filters dest=/etc/neutron/rootwrap.d/vpnaas.filters

- name: enable vpn service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - neutron-vpn-agent
    - strongswan
  notify:
    - restart vpn agent service

