##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

packages:
  - neutron-common
  - neutron-plugin-ml2
  - openvswitch-datapath-dkms
  - openvswitch-switch
  - neutron-plugin-openvswitch-agent

services:
  - neutron-plugin-openvswitch-agent
