---
- name: 'stop rabbitmq server'
  service:
    name: 'rabbitmq-server'
    state: 'stopped'

- name: 'check beam process'
  shell: 'ps ax | grep -v grep | grep beam'
  register: beam_process
  changed_when: no
  ignore_errors: yes

- name: 'kill beam processes'
  shell: 'pkill -9 beam'
  when: beam_process.stdout

- name: 'check epmd process'
  shell: 'ps ax | grep -v grep | grep epmd'
  register: epmd_process
  changed_when: no
  ignore_errors: yes

- name: 'kill epmd processes'
  shell: 'pkill -9 epmd'
  when: epmd_process.stdout

- name: 'remove mnesia directory'
  file:
    name: '/var/lib/rabbitmq/mnesia'
    state: 'absent'
