##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: destroy GPT lable
  shell: dd if=/dev/urandom of={{ physical_device }} bs=4M count=1
  ignore_errors: True

- name: create physical and group volumes
  lvg: vg=storage-volumes pvs={{ physical_device }}
       vg_options=--force
