name             'compass-rally'
maintainer       'xicheng chang'
maintainer_email 'xicheng.chang@huawei.com'
license          'All rights reserved'
description      'Installs/Configures stackforge-rally'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'yum-epel'
# depends          'python'
# depends          'openstack-common', '~> 9.0' 
