---
- hosts: controller
  sudo: True
  roles: 
    - common
    - database
    - mq
    - keystone
    - nova-controller
    - neutron-controller
    - dashboard
    - cinder-controller
    - glance
    - plumgrid
    - plumgrid-plugin

- hosts: network
  sudo: True
  roles:
    - common
    - plumgrid

- hosts: storage
  sudo: True
  roles:
    - common
    - cinder-volume

- hosts: compute
  sudo: True
  roles:
    - common
    - nova-compute
    - neutron-compute
    - plumgrid
