##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"
  tags: secgroup

- debug: msg={{ enable_secgroup }}
  tags: secgroup

- include: secgroup.yml
  when: '{{ enable_secgroup }} == False'
  tags: secgroup

- meta: flush_handlers
