##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
packages:
  - openstack-neutron-ml2
  - openstack-neutron-openvswitch

vpn_packages:
  - openstack-neutron-vpn-agent
  - strongswan

firewall_packages:
  - openstack-neutron-fwaas

services:
  - openvswitch
  - neutron-openvswitch-agent

openvswitch_agent: neutron-openvswitch-agent

xorp_packages:
  - openssl098e
  #- xorp
