##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: remove default guest user is removed
  rabbitmq_user:
    user: guest
    state: absent

- name: add rabbitmq user
  rabbitmq_user:
    user='{{ RABBIT_USER }}'
    password='{{ RABBIT_PASS }}'
    vhost=/
    configure_priv=.*
    write_priv=.*
    read_priv=.*
    state=present
