##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

controller_packages:
#  - openjdk-7-jdk
  - crudini

compute_packages:
  - crudini

service_ovs_name: openvswitch-switch
service_ovs_agent_name: neutron-plugin-openvswitch-agent

service_file:
   src: opendaylight.conf
   dst: /etc/init/opendaylight.conf
