##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: gen ceph uuid
  shell: uuidgen
  register: ceph_uuid
  run_once: true
  tags:
    - ceph_copy_secret

- name: gen template secret.xml
  local_action:
    module: "template"
    src: "secret.j2"
    dest: "/tmp/secret.xml"
    mode: "0777"
  when: inventory_hostname in groups['ceph_adm']
  tags:
    - ceph_copy_secret

- name: create pool
  shell: ceph osd pool create {{ item }} 50
  with_items:
    - volumes
    - images
    - backups
    - vms
  when: inventory_hostname in groups['ceph_adm']

- name: create ceph users for openstack
  shell: ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images' && ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
  when: inventory_hostname in groups['ceph_adm']

- name: send glance key to controller nodes
  shell: ceph auth get-or-create client.glance | tee /etc/ceph/ceph.client.glance.keyring && chown glance:glance /etc/ceph/ceph.client.glance.keyring 
  when: inventory_hostname in groups['controller']

- name: send cinder key to compute nodes
  shell: ceph auth get-or-create client.cinder | tee /etc/ceph/ceph.client.cinder.keyring && chown cinder:cinder /etc/ceph/ceph.client.cinder.keyring
  when: inventory_hostname in groups['compute']
  tags:
    - ceph_send_key

- name: copy cinder key to compute node
  shell: ceph auth get-key client.cinder | tee client.cinder.key
  when: inventory_hostname in groups['compute']
  tags:
    - ceph_copy_secret

- name: copy secret.xml to compute nodes
  copy: src="/tmp/secret.xml" dest="~/secret.xml"
  when: inventory_hostname in groups['compute']
  tags:
    - ceph_copy_secret

- name: undefine libvirt secret in case of repeatedly execute ceph_deploy
  shell: "virsh secret-list | awk '$1 ~ /[0-9]+/ {print $1}' | xargs virsh secret-undefine"
  when: inventory_hostname in groups['compute']
  tags:
    - ceph_copy_secret
  ignore_errors: True


- name: create key for libvirt on compute nodes
  shell: "virsh secret-define --file ~/secret.xml && virsh secret-set-value --secret {{ ceph_uuid.stdout_lines[0] }} --base64 $(cat client.cinder.key)"
  when: inventory_hostname in groups['compute']
  tags:
    - ceph_copy_secret
  ignore_errors: True


