##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include: heat_install.yml
  tags:
    - install
    - heat_install
    - heat

- include: heat_config.yml
  when: HA_CLUSTER is not defined or HA_CLUSTER[inventory_hostname] == ''
  tags:
    - config
    - heat_config
    - heat

- meta: flush_handlers
