---
- name: del ovs bridge
  shell: ovs-vsctl del-br br-int; ovs-vsctl del-br br-tun; ovs-vsctl del-br br-prv;

- name: remove ovs and ovs-plugin daeman
  shell: >
    sed -i '/neutron-plugin-openvswitch-agent/d' /opt/service ;
    sed -i '/openvswitch-switch/d' /opt/service ;

- name: stop ovs and ovs-plugin
  shell: service openvswitch-switch stop; service neutron-plugin-openvswitch-agent stop;

- name: remove ovs and ovs-plugin files
  shell: >
    update-rc.d -f neutron-plugin-openvswitch-agent remove;
    mv /etc/init.d/neutron-plugin-openvswitch-agent /home/neutron-plugin-openvswitch-agent;
    mv /etc/init/neutron-plugin-openvswitch-agent.conf /home/neutron-plugin-openvswitch-agent.conf;
    update-rc.d -f openvswitch-switch remove ;
    mv /etc/init.d/openvswitch-switch /home/openvswitch-switch ;
    mv /etc/init/openvswitch-switch.conf /home/openvswitch-switch.conf ;
    update-rc.d -f neutron-ovs-cleanup remove ;
    mv /etc/init.d/neutron-ovs-cleanup /home/neutron-ovs-cleanup ;
    mv /etc/init/neutron-ovs-cleanup.conf /home/neutron-ovs-cleanup.conf ;

- name: remove ovs kernel module
  shell: rmmod vport_vxlan; rmmod openvswitch;
  ignore_errors: True

- name: copy recovery script
  copy:  src={{ item }} dest=/opt/setup_networks
  with_items:
#    - recover_network_opencontrail.py
    - setup_networks_opencontrail.py

#- name: recover external script
#  shell: python /opt/setup_networks/recover_network_opencontrail.py

- name: modify net-init
  shell: sed -i 's/setup_networks.py/setup_networks_opencontrail.py/g' /etc/init.d/net_init

- name: resolve dual NIC problem
  shell: >
    echo "net.ipv4.conf.all.arp_ignore=1" >> /etc/sysctl.conf ;
    /sbin/sysctl -p ;
    echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore ;

